### ISSUE TITLE
Push button

### ISSUE THREAD

**Issue by frankiha** [s-marley/ESP32_FFT_VU#1]
Pin D2 is connected to a momentary push button which is used to change display modes, don't work for me in ground, i conected in V+ to work.

sorry my english.

**Comment by s-marley** [comment]
Thank you for letting me know. I'm away on holiday at the moment, but will
check if I have made a mistake when I get back.

**Comment by s-marley** [comment]
Hi @frankiha, just to let you know I have updated the code with a new button library (EasyButton) meaning you can now long-press to have the pattern change automatically every 10s. This also required changing the button pin from D2 to D4 as the pullup didn't want to work on pin 2. So the button should go from pin D4 to ground as shown in the images. Thanks again for bringing it to my attention.
