### ISSUE TITLE
88uS Conversion time:!!!

### ISSUE THREAD

**Issue by whatever2010** [s-marley/ESP32_FFT_VU#18]
Hi and thanks for sharing this project, I'm having a strange issue! when I ran the  sample test code on my esp32-wroom-32u the Conversion time was 88 uS and  Max sampling frequency was 11388 Hz, and it takes 90 seconds to print the output!  what am i missing here? clone or low quality board?

**Comment by TaisukeSeki** [comment]
Same problem here.

**Comment by whatever2010** [comment]
Try [this](https://github.com/silderan/esp32_is2_adc_reading) method, reading analog pin like that for this purpose is not optimal.

**Comment by TaisukeSeki** [comment]
Thank you I will try!

**Comment by whatever2010** [comment]
Thank the guy who shared this! 😂 If you are trying to make an spectrum analyzer like me just buy a SP107E. And reverse engineer that! I bought one but had no time for reversing!

**Comment by TaisukeSeki** [comment]
I would love to, but disappointingly it seems like the SP107E isn't an actual spectrum analyzer but just creates random bars of light.

**Comment by whatever2010** [comment]
Yeah but the positive side is that it has a already made app and many controlling features that the end user likes. The esp32 version has some down sides like you have to keep the volume over 50% to work, even when here is an audio amplifier! I'm going to work on this project later on. No time for now! 😅

**Comment by Cowh3adDK** [comment]
> Hi and thanks for sharing this project, I'm having a strange issue! when I ran the sample test code on my esp32-wroom-32u the Conversion time was 88 uS and Max sampling frequency was 11388 Hz, and it takes 90 seconds to print the output! what am i missing here? clone or low quality board?

after testing my own boards, all with clone esp modules have about the same conversion time as you, and my originals all have good conversion time.

**Comment by whatever2010** [comment]
Hello mate, Thank you for letting us know.
